"""empty message

Revision ID: 69bfc25d346e
Revises: 74cbc5bf6578
Create Date: 2018-09-11 13:22:43.058348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69bfc25d346e'
down_revision = '74cbc5bf6578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EveChars',
    sa.Column('character_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('character_owner_hash', sa.String(length=100), nullable=True),
    sa.Column('character_name', sa.String(length=200), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.drop_table('eve_char')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eve_char',
    sa.Column('character_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('character_owner_hash', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('character_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('access_token_expires', mysql.DATETIME(), nullable=True),
    sa.Column('refresh_token', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('character_id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('EveChars')
    # ### end Alembic commands ###
